name: Ejecutar bot manualmente

on:
  workflow_dispatch:  # Ejecutarlo a mano

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar el repositorio
      uses: actions/checkout@v3

    - name: Instalar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Instalar dependencias
      run: npm install

    - name: Ejecutar bot
      run: node main.js
